apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
  namespace: database
spec:
  serviceName: database
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: postgres:16
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: demo
        - name: POSTGRES_USER
          value: demo
        - name: POSTGRES_PASSWORD
          value: demo123
