apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-controller
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress
  template:
    metadata:
      labels:
        app: ingress
    spec:
      containers:
      - name: ingress
        image: registry.k8s.io/ingress-nginx/controller:v1.11.1
        ports:
        - containerPort: 80
